# IMPORT

In [40]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder


In [41]:
df = pd.read_csv('employee_promotion.csv')

In [42]:
df.head()

employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   
1               other                1   30                   5.0   
2            sourcing                1   34                   3.0   
3               other                2   39                   1.0   
4               other                1   45                   3.0   

   length_of_service  awards_won  avg_training_score  is_promoted  
0                  8           0                49.0  no_promoted  
1                  4           0                60.0  no_promoted  
2                  7           0                50.0  no_promoted  
3                 10           0                50.0  no_promoted  
4                  2           0                73.0  no_promoted

# Data Split
## x = Data Frame tanpa label
## y = Label

In [43]:
y = df.iloc[:,-1]
X = df.iloc[:,:-1]

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [45]:
print("Dimensi X_train : ", X_train.shape)
print("Dimensi X_train : ", X_test.shape)
print("Dimensi y_train : ", y_train.shape)
print("Dimensi y_test : ", y_test.shape)

Dimensi X_train :  (38365, 12)
Dimensi X_train :  (16443, 12)
Dimensi y_train :  (38365,)
Dimensi y_test :  (16443,)


# Data Normalisasi

In [46]:
df2 = df[['age', 'no_of_trainings', 'avg_training_score']]
df2.head()

age  no_of_trainings  avg_training_score
0   35                1                49.0
1   30                1                60.0
2   34                1                50.0
3   39                2                50.0
4   45                1                73.0

In [47]:
norm = MinMaxScaler()

In [48]:
Scaled_data = norm.fit_transform(df2)

In [49]:
print("Nilai Data Sebelum Scaling : ")
print(df2)
print("Nilai Standar Deviasi: \n", np.std(df2))

print("\n\n Nilai Data setelah Scaling : ")
print(Scaled_data)
print("Nilai Standar Deviasi: ", np.std(Scaled_data))

Nilai Data Sebelum Scaling : 
       age  no_of_trainings  avg_training_score
0       35                1                49.0
1       30                1                60.0
2       34                1                50.0
3       39                2                50.0
4       45                1                73.0
...    ...              ...                 ...
54803   48                1                78.0
54804   37                1                56.0
54805   27                1                79.0
54806   29                1                 NaN
54807   27                1                49.0

[54808 rows x 3 columns]
Nilai Standar Deviasi: 
 age                    7.660099
no_of_trainings        0.609258
avg_training_score    13.521781
dtype: float64


 Nilai Data setelah Scaling : 
[[0.375      0.         0.16666667]
 [0.25       0.         0.35      ]
 [0.35       0.         0.18333333]
 ...
 [0.175      0.         0.66666667]
 [0.225      0.                nan]
 [0.175      0

# Data Standarisasi

In [50]:
df3 = df[['age', 'no_of_trainings', 'avg_training_score']]
df3.head()

age  no_of_trainings  avg_training_score
0   35                1                49.0
1   30                1                60.0
2   34                1                50.0
3   39                2                50.0
4   45                1                73.0

In [51]:
stand = StandardScaler()


In [52]:
Scaled_data = stand.fit_transform(df3)

In [53]:
print("Nilai Data Sebelum Scaling : ")
print(df3)
print("Nilai Standar Deviasi: \n", np.std(df3))

print("\n\n Nilai Data Setelah Scaling : ")
print(Scaled_data)
print("Nilai Standar Deviasi: ", np.std(Scaled_data))

Nilai Data Sebelum Scaling : 
       age  no_of_trainings  avg_training_score
0       35                1                49.0
1       30                1                60.0
2       34                1                50.0
3       39                2                50.0
4       45                1                73.0
...    ...              ...                 ...
54803   48                1                78.0
54804   37                1                56.0
54805   27                1                79.0
54806   29                1                 NaN
54807   27                1                49.0

[54808 rows x 3 columns]
Nilai Standar Deviasi: 
 age                    7.660099
no_of_trainings        0.609258
avg_training_score    13.521781
dtype: float64


 Nilai Data Setelah Scaling : 
[[ 0.02559817 -0.41527615 -1.08803998]
 [-0.62713488 -0.41527615 -0.27453765]
 [-0.10494844 -0.41527615 -1.01408522]
 ...
 [-1.01877471 -0.41527615  1.13060275]
 [-0.75768149 -0.41527615         nan]

# Data Cleaning Nilai Null

In [54]:
df.isna().sum()

employee_id                0
department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
awards_won                 0
avg_training_score      2560
is_promoted                0
dtype: int64

In [55]:
df.dtypes

employee_id               int64
department               object
region                   object
education                object
gender                   object
recruitment_channel      object
no_of_trainings           int64
age                       int64
previous_year_rating    float64
length_of_service         int64
awards_won                int64
avg_training_score      float64
is_promoted              object
dtype: object

In [56]:
imputer = SimpleImputer(strategy='most_frequent' )

In [57]:
df["education"] = imputer.fit_transform(df[["education"]])

In [58]:
df.isna().sum()

employee_id                0
department                 0
region                     0
education                  0
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
awards_won                 0
avg_training_score      2560
is_promoted                0
dtype: int64

In [59]:
imputer2 = SimpleImputer(strategy='mean' )

In [60]:
df["previous_year_rating"] = imputer2.fit_transform(df[["previous_year_rating"]])
df["avg_training_score"] = imputer2.fit_transform(df[["avg_training_score"]])

In [61]:
df.isna().sum()

employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
awards_won              0
avg_training_score      0
is_promoted             0
dtype: int64

# Data Cleaning Nilai Duplikat

In [62]:
df[df.duplicated()]

Empty DataFrame
Columns: [employee_id, department, region, education, gender, recruitment_channel, no_of_trainings, age, previous_year_rating, length_of_service, awards_won, avg_training_score, is_promoted]
Index: []

In [63]:
df.iloc[0]

employee_id                         65438
department              Sales & Marketing
region                           region_7
education                Master's & above
gender                                  f
recruitment_channel              sourcing
no_of_trainings                         1
age                                    35
previous_year_rating                  5.0
length_of_service                       8
awards_won                              0
avg_training_score                   49.0
is_promoted                   no_promoted
Name: 0, dtype: object

In [64]:
df = df.append(df.iloc[0:100])

C:\Users\NITRO 5\AppData\Local\Temp\ipykernel_8544\324845436.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df.iloc[0:100])


In [65]:
df[df.duplicated()]

employee_id         department     region         education gender  \
0         65438  Sales & Marketing   region_7  Master's & above      f   
1         65141         Operations  region_22        Bachelor's      m   
2          7513  Sales & Marketing  region_19        Bachelor's      m   
3          2542  Sales & Marketing  region_23        Bachelor's      m   
4         48945         Technology  region_26        Bachelor's      m   
..          ...                ...        ...               ...    ...   
95        43923          Analytics  region_14        Bachelor's      m   
96        64109         Technology  region_26        Bachelor's      f   
97        41983         Operations   region_2        Bachelor's      f   
98        21440  Sales & Marketing  region_31        Bachelor's      m   
99        51256            Finance   region_2  Master's & above      m   

   recruitment_channel  no_of_trainings  age  previous_year_rating  \
0             sourcing                1   35              5.000000   
1                other                1   30              5.000000   
2             sourcing                1   34              3.000000   
3                other                2   39              1.000000   
4                other                1   45              3.000000   
..                 ...              ...  ...                   ...   
95            sourcing                1   31              4.000000   
96            sourcing                1   23              3.329256   
97            sourcing                1   33              3.000000   
98               other                1   41              3.000000   
99               other                1   60              5.000000   

    length_of_service  awards_won  avg_training_score  is_promoted  
0                   8           0                49.0  no_promoted  
1                   4           0                60.0  no_promoted  
2                   7           0                50.0  no_promoted  
3                  10           0                50.0  no_promoted  
4                   2           0                73.0  no_promoted  
..                ...         ...                 ...          ...  
95                  4           0                86.0  no_promoted  
96                  1           0                77.0  no_promoted  
97                  5           0                57.0  no_promoted  
98                 12           0                52.0  no_promoted  
99                 17           0                59.0  no_promoted  

[100 rows x 13 columns]

In [66]:
df.drop_duplicates(inplace=True)

In [67]:
df[df.duplicated()]

Empty DataFrame
Columns: [employee_id, department, region, education, gender, recruitment_channel, no_of_trainings, age, previous_year_rating, length_of_service, awards_won, avg_training_score, is_promoted]
Index: []

# Ganti Tipe Data

In [68]:
df['length_of_service'] = df['length_of_service'].astype('float64')

In [69]:
df.dtypes

employee_id               int64
department               object
region                   object
education                object
gender                   object
recruitment_channel      object
no_of_trainings           int64
age                       int64
previous_year_rating    float64
length_of_service       float64
awards_won                int64
avg_training_score      float64
is_promoted              object
dtype: object

In [70]:
df.head()

employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   
1               other                1   30                   5.0   
2            sourcing                1   34                   3.0   
3               other                2   39                   1.0   
4               other                1   45                   3.0   

   length_of_service  awards_won  avg_training_score  is_promoted  
0                8.0           0                49.0  no_promoted  
1                4.0           0                60.0  no_promoted  
2                7.0           0                50.0  no_promoted  
3               10.0           0                50.0  no_promoted  
4                2.0           0                73.0  no_promoted

# ENCODE

In [71]:
df.head()

employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   
1               other                1   30                   5.0   
2            sourcing                1   34                   3.0   
3               other                2   39                   1.0   
4               other                1   45                   3.0   

   length_of_service  awards_won  avg_training_score  is_promoted  
0                8.0           0                49.0  no_promoted  
1                4.0           0                60.0  no_promoted  
2                7.0           0                50.0  no_promoted  
3               10.0           0                50.0  no_promoted  
4                2.0           0                73.0  no_promoted

In [72]:
encoder = OneHotEncoder(sparse=False)
genderEncode = encoder.fit_transform(df[["gender"]])

In [73]:
gender = pd.DataFrame(genderEncode)
df = df.join(gender)
df.head()

employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   
1               other                1   30                   5.0   
2            sourcing                1   34                   3.0   
3               other                2   39                   1.0   
4               other                1   45                   3.0   

   length_of_service  awards_won  avg_training_score  is_promoted    0    1  
0                8.0           0                49.0  no_promoted  1.0  0.0  
1                4.0           0                60.0  no_promoted  0.0  1.0  
2                7.0           0                50.0  no_promoted  0.0  1.0  
3               10.0           0                50.0  no_promoted  0.0  1.0  
4                2.0           0                73.0  no_promoted  0.0  1.0

In [74]:
df = df.rename(columns={
    0 : 'Female',
    1 : 'Male'
})
df.head()

employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   
1               other                1   30                   5.0   
2            sourcing                1   34                   3.0   
3               other                2   39                   1.0   
4               other                1   45                   3.0   

   length_of_service  awards_won  avg_training_score  is_promoted  Female  \
0                8.0           0                49.0  no_promoted     1.0   
1                4.0           0                60.0  no_promoted     0.0   
2                7.0           0                50.0  no_promoted     0.0   
3               10.0           0                50.0  no_promoted     0.0   
4                2.0           0                73.0  no_promoted     0.0   

   Male  
0   0.0  
1   1.0  
2   1.0  
3   1.0  
4   1.0

In [75]:
encoder = OneHotEncoder(sparse=False)
promotEncode = encoder.fit_transform(df[["is_promoted"]])

In [76]:
promot = pd.DataFrame(promotEncode)
df = df.join(promot)

In [77]:
df = df.rename(columns={
    0 : 'No Promoted',
    1 : 'Has Promoted'
})
df.head(50)

employee_id         department     region         education gender  \
0         65438  Sales & Marketing   region_7  Master's & above      f   
1         65141         Operations  region_22        Bachelor's      m   
2          7513  Sales & Marketing  region_19        Bachelor's      m   
3          2542  Sales & Marketing  region_23        Bachelor's      m   
4         48945         Technology  region_26        Bachelor's      m   
5         58896          Analytics   region_2        Bachelor's      m   
6         20379         Operations  region_20        Bachelor's      f   
7         16290         Operations  region_34  Master's & above      m   
8         73202          Analytics  region_20        Bachelor's      m   
9         28911  Sales & Marketing   region_1  Master's & above      m   
10        29934         Technology  region_23        Bachelor's      m   
11        49017  Sales & Marketing   region_7        Bachelor's      f   
12        60051  Sales & Marketing   region_4        Bachelor's      m   
13        38401         Technology  region_29  Master's & above      m   
14        77040                R&D   region_2  Master's & above      m   
15        43931         Operations   region_7        Bachelor's      m   
16         7152         Technology   region_2        Bachelor's      m   
17         9403  Sales & Marketing  region_31        Bachelor's      m   
18        17436  Sales & Marketing  region_31        Bachelor's      m   
19        54461         Operations  region_15        Bachelor's      m   
20        12067        Procurement  region_14        Bachelor's      m   
21        33332         Operations  region_15        Bachelor's      m   
22        58789            Finance  region_11        Bachelor's      f   
23        71177        Procurement   region_5        Bachelor's      m   
24        52057            Finance  region_22  Master's & above      m   
25        26585         Technology  region_22        Bachelor's      m   
26        37749        Procurement  region_26        Bachelor's      m   
27         2370         Technology  region_26        Bachelor's      m   
28         8219          Analytics   region_5        Bachelor's      m   
29        74759  Sales & Marketing   region_4        Bachelor's      m   
30        27395        Procurement  region_15        Bachelor's      m   
31        58536            Finance  region_31        Bachelor's      m   
32        35465  Sales & Marketing   region_7        Bachelor's      f   
33        51756         Operations   region_2        Bachelor's      m   
34        57011          Analytics  region_22        Bachelor's      m   
35        77064  Sales & Marketing  region_22        Bachelor's      m   
36        64062         Technology  region_28        Bachelor's      m   
37        47123  Sales & Marketing   region_7        Bachelor's      f   
38        56275  Sales & Marketing   region_1  Master's & above      m   
39        58304  Sales & Marketing  region_28        Bachelor's      m   
40        25014         Technology  region_15        Bachelor's      m   
41        40097         Operations   region_2        Bachelor's      f   
42        23560                 HR   region_2        Bachelor's      m   
43        17423  Sales & Marketing   region_2        Bachelor's      m   
44        61758          Analytics   region_2        Bachelor's      m   
45        75009        Procurement  region_17        Bachelor's      f   
46        17876        Procurement  region_13  Master's & above      f   
47        36924         Technology  region_16        Bachelor's      m   
48        50408  Sales & Marketing  region_20        Bachelor's      m   
49        18013        Procurement   region_2  Master's & above      f   

   recruitment_channel  no_of_trainings  age  previous_year_rating  \
0             sourcing                1   35              5.000000   
1                other                1   30              5.000000   
2             sourc

In [78]:
df.to_csv("clean_employee_promotion.csv", index=False)