# Posttest 7
## Gempar Panggih Dwi Putra
## NIM 2009106022
## INFORMATIKA A 2020
## Mata Kuliah Kecerdasan Buatan

In [1]:
import tensorflow as tf

## 1. Membuat Variabel random_tensor dengan shape (5,5) menggunakan tf.random

In [2]:
#penggunaan tf.random.normal()
random_tensor = tf.random.normal([5,5],mean=0.0,stddev=1.0)

#Pengecekan nilai constant
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.11868419, -1.1266984 ,  0.45057097, -1.4395093 ,  1.4209099 ],
       [-1.3744923 , -0.35206094, -2.7595553 , -2.286236  , -0.38906977],
       [ 0.82440144, -0.25657386, -0.24320799, -0.50847125, -0.64022815],
       [ 0.21280043,  0.7008021 , -0.28851408,  1.4548473 ,  0.49500328],
       [-0.7132273 ,  1.731316  , -0.04284858, -0.71515995, -0.42518032]],
      dtype=float32)>

## 2. Membuat Variabel prime_tensor dengan shape (5,5) berisi bilangan prima menggunakan list

In [3]:
#Pembuatan list untuk dimasukkan kedalam Tensor
list_f = [[2,3,5,7,11],[13,17,19,23,29],[31,37,41,43,47],[53,59,61,67,71],[73,79,83,89,97]]

#Penggunaan tf.convert_to_tensor
prime_tensor = tf.convert_to_tensor(list_f, dtype=tf.float32)

#Pengecekan nilai constant
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

## 3. Menampilkan dimensi dari variabel random_tensor dan prime_tensor

In [4]:
random_tensor.shape

TensorShape([5, 5])

In [5]:
prime_tensor.shape

TensorShape([5, 5])

## 4. Operasi Aritmaika antara variabel random tensor dengan prime_tensor

In [6]:
print("Hasil dari Penjumlahan adalah:\n",tf.add(random_tensor, prime_tensor).numpy())

Hasil dari Penjumlahan adalah:
 [[ 1.8813158  1.8733016  5.450571   5.5604906 12.42091  ]
 [11.625507  16.64794   16.240444  20.713764  28.61093  ]
 [31.824402  36.743427  40.75679   42.491528  46.35977  ]
 [53.2128    59.7008    60.711487  68.45485   71.495    ]
 [72.28677   80.731316  82.95715   88.28484   96.57482  ]]


In [7]:
print("Hasil dari Perkalian adalah:\n",tf.multiply(random_tensor, prime_tensor).numpy())

Hasil dari Perkalian adalah:
 [[ -0.23736838  -3.380095     2.2528548  -10.076565    15.630009  ]
 [-17.8684      -5.985036   -52.431553   -52.583427   -11.283023  ]
 [ 25.556444    -9.493233    -9.971528   -21.864264   -30.090723  ]
 [ 11.278422    41.347324   -17.59936     97.47477     35.145233  ]
 [-52.06559    136.77396     -3.5564325  -63.649235   -41.24249   ]]


In [8]:
print("Hasil dari Pengurangan adalah:\n",tf.subtract(random_tensor, prime_tensor).numpy())

Hasil dari Pengurangan adalah:
 [[ -2.1186843  -4.1266985  -4.549429   -8.439509   -9.57909  ]
 [-14.374493  -17.35206   -21.759556  -25.286236  -29.38907  ]
 [-30.175598  -37.256573  -41.24321   -43.508472  -47.64023  ]
 [-52.7872    -58.2992    -61.288513  -65.54515   -70.505    ]
 [-73.71323   -77.268684  -83.04285   -89.71516   -97.42518  ]]


In [9]:
print("Hasil dari Pembagian adalah:\n",tf.divide(random_tensor, prime_tensor).numpy())

Hasil dari Pembagian adalah:
 [[-0.05934209 -0.37556612  0.09011419 -0.20564418  0.12917362]
 [-0.10573018 -0.02070947 -0.14523976 -0.09940157 -0.0134162 ]
 [ 0.02659359 -0.00693443 -0.0059319  -0.01182491 -0.01362188]
 [ 0.0040151   0.011878   -0.00472974  0.02171414  0.00697188]
 [-0.00977024  0.02191539 -0.00051625 -0.00803551 -0.0043833 ]]


In [10]:
print("Hasil dari Pemangkatan adalah:\n",tf.pow(random_tensor, prime_tensor).numpy())

Hasil dari Pemangkatan adalah:
 [[ 1.4085936e-02 -1.4302864e+00  1.8570177e-02 -1.2808588e+01
   4.7668545e+01]
 [-6.2495678e+01 -1.9611166e-08 -2.3765286e+08 -1.8187984e+08
  -1.2906159e-12]
 [ 2.5136278e-03 -1.3831168e-22 -6.6848468e-26 -2.3412904e-13
  -7.9019458e-10]
 [ 2.4129170e-36  7.7647566e-10 -1.1754050e-33  8.1052672e+10
   2.0757432e-22]
 [-1.9303663e-11  6.7878224e+18 -0.0000000e+00 -1.1012442e-13
  -9.3668933e-37]]


## 5. Tampilkan Nilai Maksimal dan Minimal dari random_tensor

In [11]:
tf.argmax(random_tensor, axis=0).numpy()

array([2, 4, 0, 3, 0], dtype=int64)

In [12]:
tf.argmin(random_tensor, axis=0).numpy()

array([1, 0, 1, 1, 2], dtype=int64)

## 6. Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [13]:
# Sebelum
print(f"Size Awal : {random_tensor.shape} {prime_tensor.shape}" )

Size Awal : (5, 5) (5, 5)


In [14]:
# Setelah
concat_tensor_1 = tf.concat([random_tensor, prime_tensor], axis=0)
concat_tensor_2 = tf.concat([random_tensor, prime_tensor], axis=1)
print(f"Size yang sudah di concat (axis = 0) : {concat_tensor_1.shape}")
print(f"Size yang sudah di concat (axis = 1) : {concat_tensor_2.shape}")

Size yang sudah di concat (axis = 0) : (10, 5)
Size yang sudah di concat (axis = 1) : (5, 10)


## 7. Sorting random tensor dan prime tensor secara descending

In [15]:
# Sorting random_tensor secara descending
tf.sort(random_tensor, direction="DESCENDING").numpy()

array([[ 1.4209099 ,  0.45057097, -0.11868419, -1.1266984 , -1.4395093 ],
       [-0.35206094, -0.38906977, -1.3744923 , -2.286236  , -2.7595553 ],
       [ 0.82440144, -0.24320799, -0.25657386, -0.50847125, -0.64022815],
       [ 1.4548473 ,  0.7008021 ,  0.49500328,  0.21280043, -0.28851408],
       [ 1.731316  , -0.04284858, -0.42518032, -0.7132273 , -0.71515995]],
      dtype=float32)

In [16]:
# Sorting random_tensor secara descending
tf.sort(prime_tensor, direction="DESCENDING").numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)