# Klasifikasi Dataset Iris dari SKLEARN dengan Neural Network Sederhana

### Gempar Panggih Dwi Putra
### NIM 2009106022
### INFORMATIKA A2 2020


## Import

In [103]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from keras.layers import Dense
from keras.optimizers import Adam
from keras.models import Sequential

## Preprocessing

### Load Datasets

In [104]:
df = load_iris()

In [105]:
print('Example data: ')
print(df.data[:5])
print('Example labels: ')
print(df.target[:5])

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
[0 0 0 0 0]


### Reshape

In [106]:
x = df.data
yx = df.target.reshape(-1, 1)

### One Hot Encode

In [107]:
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(yx)

### Split Data

In [108]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

## Modelling

### Model Sequential

In [109]:
model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='var1'))
model.add(Dense(10, activation='relu', name='var2'))
model.add(Dense(3, activation='softmax', name='output'))

### Compile Model

In [110]:
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

c:\Users\NITRO 5\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


### Model Summary

In [111]:
print('Summary: ')
print(model.summary())

Summary: 
Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 var1 (Dense)                (None, 10)                50        
                                                                 
 var2 (Dense)                (None, 10)                110       
                                                                 
 output (Dense)              (None, 3)                 33        
                                                                 
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None


### Training Model

In [112]:
history = model.fit(x_train, y_train, verbose=2, batch_size=25, epochs=200, validation_data=(x, y))

Epoch 1/200
5/5 - 0s - loss: 1.1151 - accuracy: 0.3750 - val_loss: 1.0980 - val_accuracy: 0.3267 - 334ms/epoch - 67ms/step
Epoch 2/200
5/5 - 0s - loss: 1.0580 - accuracy: 0.3661 - val_loss: 1.0445 - val_accuracy: 0.3267 - 49ms/epoch - 10ms/step
Epoch 3/200
5/5 - 0s - loss: 1.0157 - accuracy: 0.3571 - val_loss: 0.9978 - val_accuracy: 0.3333 - 53ms/epoch - 11ms/step
Epoch 4/200
5/5 - 0s - loss: 0.9750 - accuracy: 0.3661 - val_loss: 0.9679 - val_accuracy: 0.3467 - 29ms/epoch - 6ms/step
Epoch 5/200
5/5 - 0s - loss: 0.9452 - accuracy: 0.3839 - val_loss: 0.9526 - val_accuracy: 0.3533 - 29ms/epoch - 6ms/step
Epoch 6/200
5/5 - 0s - loss: 0.9287 - accuracy: 0.3929 - val_loss: 0.9386 - val_accuracy: 0.3333 - 25ms/epoch - 5ms/step
Epoch 7/200
5/5 - 0s - loss: 0.9137 - accuracy: 0.3750 - val_loss: 0.9238 - val_accuracy: 0.3333 - 25ms/epoch - 5ms/step
Epoch 8/200
5/5 - 0s - loss: 0.8973 - accuracy: 0.3750 - val_loss: 0.9074 - val_accuracy: 0.3467 - 36ms/epoch - 7ms/step
Epoch 9/200
5/5 - 0s - loss:

Bisa dilihat dari hasil training diatas, akurasi dan validasi sudah diatas 70% sehingga sudah memenuhi kententuan.

In [113]:
print("Akurasi validasi :", history.history["val_accuracy"][-1])

Akurasi validasi : 0.9599999785423279


## Evaluate

In [114]:
result = model.evaluate(x_test, y_test)
print('Hasil Tes Loss: {:4f}'.format(result[0]))
print('Hasil Tes Akurasi : {:4f}'.format(result[1]))

2/2 [==============================] - 0s 2ms/step - loss: 0.0683 - accuracy: 0.9737
Hasil Tes Loss: 0.068286
Hasil Tes Akurasi : 0.973684
