# Klasifikasi Dataset Iris dari SKLEARN dengan Neural Network Sederhana

### Gempar Panggih Dwi Putra
### NIM 2009106022
### INFORMATIKA A2 2020


## Import

In [12]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from keras.layers import Dense
from keras.optimizers import Adam
from keras.models import Sequential

## Preprocessing

### Load Datasets

In [13]:
df = load_iris()

In [14]:
print('Example data: ')
print(df.data[:5])
print('Example labels: ')
print(df.target[:5])

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
[0 0 0 0 0]


### Reshape

In [15]:
x = df.data
yx = df.target.reshape(-1, 1)

### One Hot Encode

In [16]:
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(yx)

### Split Data

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

## Modelling

### Model Sequential

In [18]:
model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='var1'))
model.add(Dense(10, activation='relu', name='var2'))
model.add(Dense(3, activation='softmax', name='output'))

### Optimizer Model

In [19]:
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

c:\Users\NITRO 5\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


### Model Summary

In [20]:
print('Summary: ')
print(model.summary())

Summary: 
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 var1 (Dense)                (None, 10)                50        
                                                                 
 var2 (Dense)                (None, 10)                110       
                                                                 
 output (Dense)              (None, 3)                 33        
                                                                 
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None


### Training Model

In [21]:
model.fit(x_train, y_train, verbose=2, batch_size=25, epochs=200, validation_data=(x, y))

Epoch 1/200
5/5 - 0s - loss: 1.2175 - accuracy: 0.3571 - val_loss: 1.2154 - val_accuracy: 0.3333 - 342ms/epoch - 68ms/step
Epoch 2/200
5/5 - 0s - loss: 1.1757 - accuracy: 0.3571 - val_loss: 1.1710 - val_accuracy: 0.3333 - 18ms/epoch - 4ms/step
Epoch 3/200
5/5 - 0s - loss: 1.1354 - accuracy: 0.3571 - val_loss: 1.1336 - val_accuracy: 0.3333 - 35ms/epoch - 7ms/step
Epoch 4/200
5/5 - 0s - loss: 1.1027 - accuracy: 0.3571 - val_loss: 1.1018 - val_accuracy: 0.3333 - 29ms/epoch - 6ms/step
Epoch 5/200
5/5 - 0s - loss: 1.0754 - accuracy: 0.3571 - val_loss: 1.0748 - val_accuracy: 0.3333 - 33ms/epoch - 7ms/step
Epoch 6/200
5/5 - 0s - loss: 1.0532 - accuracy: 0.3571 - val_loss: 1.0523 - val_accuracy: 0.3333 - 31ms/epoch - 6ms/step
Epoch 7/200
5/5 - 0s - loss: 1.0327 - accuracy: 0.3571 - val_loss: 1.0345 - val_accuracy: 0.3333 - 33ms/epoch - 7ms/step
Epoch 8/200
5/5 - 0s - loss: 1.0181 - accuracy: 0.3571 - val_loss: 1.0189 - val_accuracy: 0.3333 - 32ms/epoch - 6ms/step
Epoch 9/200
5/5 - 0s - loss: 1

Bisa dilihat dari hasil training diatas, akurasi dan validasi sudah diatas 70% sehingga sudah memenuhi kententuan.

## Evaluate

In [27]:
result = model.evaluate(x_test, y_test)
print('Hasil Tes Loss: {:4f}'.format(result[0]))
print('Hasil Tes Akurasi : {:4f}'.format(result[1]))

2/2 [==============================] - 0s 2ms/step - loss: 0.1226 - accuracy: 0.9737
Hasil Tes Loss: 0.122640
Hasil Tes Akurasi : 0.973684
[[4.9 3.1 1.5 0.1]
 [6.9 3.2 5.7 2.3]
 [6.7 3.1 5.6 2.4]
 [6.4 2.8 5.6 2.1]
 [5.4 3.9 1.3 0.4]
 [4.4 2.9 1.4 0.2]
 [5.1 3.5 1.4 0.3]
 [6.4 2.9 4.3 1.3]
 [6.3 2.3 4.4 1.3]
 [5.1 3.5 1.4 0.2]
 [4.8 3.  1.4 0.3]
 [6.7 3.1 4.7 1.5]
 [4.9 3.1 1.5 0.2]
 [6.7 3.3 5.7 2.1]
 [5.6 2.5 3.9 1.1]
 [5.7 3.  4.2 1.2]
 [5.5 2.4 3.7 1. ]
 [7.7 3.  6.1 2.3]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [5.4 3.4 1.7 0.2]
 [5.8 2.7 4.1 1. ]
 [5.1 3.3 1.7 0.5]
 [6.5 2.8 4.6 1.5]
 [6.7 2.5 5.8 1.8]
 [5.9 3.  5.1 1.8]
 [6.1 2.9 4.7 1.4]
 [7.2 3.  5.8 1.6]
 [4.7 3.2 1.3 0.2]
 [6.8 3.2 5.9 2.3]
 [5.2 4.1 1.5 0.1]
 [6.2 2.9 4.3 1.3]
 [6.3 3.3 4.7 1.6]
 [6.2 2.2 4.5 1.5]
 [6.7 3.1 4.4 1.4]
 [6.7 3.3 5.7 2.5]
 [4.3 3.  1.1 0.1]
 [5.5 3.5 1.3 0.2]]
