# Klasifikasi Dataset Iris dari SKLEARN dengan Neural Network Sederhana

### Gempar Panggih Dwi Putra
### NIM 2009106022
### INFORMATIKA A2 2020


## Import

In [29]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from keras.layers import Dense
from keras.optimizers import Adam
from keras.models import Sequential

## Preprocessing

### Load Datasets

In [30]:
df = load_iris()

In [31]:
print('Example data: ')
print(df.data[:5])
print('Example labels: ')
print(df.target[:5])

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
[0 0 0 0 0]


### Reshape

In [32]:
x = df.data
yx = df.target.reshape(-1, 1)

### One Hot Encode

In [33]:
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(yx)

### Split Data

In [34]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

## Modelling

### Model Sequential

In [35]:
model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='var1'))
model.add(Dense(10, activation='relu', name='var2'))
model.add(Dense(3, activation='softmax', name='output'))

### Optimizer Model

In [36]:
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

c:\Users\NITRO 5\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


### Model Summary

In [37]:
print('Summary: ')
print(model.summary())

Summary: 
Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 var1 (Dense)                (None, 10)                50        
                                                                 
 var2 (Dense)                (None, 10)                110       
                                                                 
 output (Dense)              (None, 3)                 33        
                                                                 
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None


### Training Model

In [38]:
model.fit(x_train, y_train, verbose=2, batch_size=25, epochs=200, validation_data=(x, y))

Epoch 1/200
5/5 - 0s - loss: 1.3738 - accuracy: 0.3393 - val_loss: 1.3406 - val_accuracy: 0.3333 - 354ms/epoch - 71ms/step
Epoch 2/200
5/5 - 0s - loss: 1.3021 - accuracy: 0.3393 - val_loss: 1.2759 - val_accuracy: 0.3333 - 32ms/epoch - 6ms/step
Epoch 3/200
5/5 - 0s - loss: 1.2463 - accuracy: 0.3393 - val_loss: 1.2192 - val_accuracy: 0.3333 - 27ms/epoch - 5ms/step
Epoch 4/200
5/5 - 0s - loss: 1.1895 - accuracy: 0.3393 - val_loss: 1.1716 - val_accuracy: 0.3333 - 34ms/epoch - 7ms/step
Epoch 5/200
5/5 - 0s - loss: 1.1455 - accuracy: 0.3393 - val_loss: 1.1295 - val_accuracy: 0.3333 - 23ms/epoch - 5ms/step
Epoch 6/200
5/5 - 0s - loss: 1.1085 - accuracy: 0.3393 - val_loss: 1.0931 - val_accuracy: 0.3333 - 42ms/epoch - 8ms/step
Epoch 7/200
5/5 - 0s - loss: 1.0724 - accuracy: 0.3393 - val_loss: 1.0609 - val_accuracy: 0.3333 - 27ms/epoch - 5ms/step
Epoch 8/200
5/5 - 0s - loss: 1.0426 - accuracy: 0.3393 - val_loss: 1.0311 - val_accuracy: 0.3333 - 44ms/epoch - 9ms/step
Epoch 9/200
5/5 - 0s - loss: 1

Bisa dilihat dari hasil training diatas, akurasi dan validasi sudah diatas 70% sehingga sudah memenuhi kententuan.

## Evaluate

In [39]:
result = model.evaluate(x_test, y_test)
print('Hasil Tes Loss: {:4f}'.format(result[0]))
print('Hasil Tes Akurasi : {:4f}'.format(result[1]))

2/2 [==============================] - 0s 2ms/step - loss: 0.1236 - accuracy: 0.9474
Hasil Tes Loss: 0.123624
Hasil Tes Akurasi : 0.947368
